.\" Manpage for savemysqldb.
.\" Contact mbouchar@gmail.com to correct errors or typos.
.TH man 1 "28 Mar 2015" "1.0" "savemysqldb man page"
.SH NAME
savemysqldb \- backup MySQL databases
.SH SYNOPSIS
saveuserdb [DATABASE]
.SH DESCRIPTION
savemysqldb is high level program for creating MySQL database backups.
.SH OPTIONS
The savemysqldb does not take any options. However, you can edit the configuration file located at /etc/savemysqldb.conf.
.SH BUGS
No known bugs.
.SH AUTHOR
Mathieu Bouchard (mbouchar@gmail.com)
